In [14]:
import numpy as np

In [15]:
matriksA = np.array([[1,0], [3,2]])
print(matriksA)

[[1 0]
 [3 2]]


In [16]:
matriksB = np.array([[0,0], [7,9]])
print(matriksB)

[[0 0]
 [7 9]]


In [19]:
matriksC = matriksA + matriksB
print(matriksC)

[[ 1  0]
 [10 11]]


In [21]:
matriksD = matriksA - matriksB
print(matriksD)

[[ 1  0]
 [-4 -7]]


In [23]:
matriksE = matriksA * matriksB
print(matriksE)

[[ 0  0]
 [21 18]]
